# config context path to "/" by setting an empty string
server:
  contextPath:
  port: 8081

# JACKSON
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  h2:
    console:
      enabled: true

jwt:
  header: Authorization
  secret: mySecret
  expiration: 3600
  route:
    authentication:
      path: auth
      refresh: refresh

#spring:
#  h2:
#    console:
#      enabled: true

logging:
  level:
    org.springframework:
      security: DEBUG